server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/esercizio1
    username: root
    password: password
    
  jpa:
    hibernate:
      ddl-auto: update



userphisicaldelete: false